op_version_set = 0
def forward(self,
    x: Tensor) -> Tensor:
  _0 = ops.prim.NumToTensor(torch.size(x, 0))
  _1 = int(_0)
  _2 = int(_0)
  _3 = ops.prim.NumToTensor(torch.size(x, 1))
  _4 = int(_3)
  input_1 = torch.view(x, [_2, int(_3), 1])
  input_2 = torch._convolution(input_1, getattr(getattr(self.Layers, "3"), "0").weight, getattr(getattr(self.Layers, "3"), "0").bias, [1], [0], [1], False, [0], 16, False, False, True)
  _5 = torch.view(torch.threshold(input_2, 0., 0.), [_1, _4])
  _6 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _7 = torch.select(torch.unsqueeze(CONSTANTS.c1, 1), 2, 0)
  _8 = torch.to(_6, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _9 = torch.index(_7, [_8])
  _10 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _11 = torch.select(torch.unsqueeze(_5, 1), 2, 11)
  _12 = torch.to(_10, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _13 = torch.index(_11, [_12])
  _14 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _15 = torch.select(torch.unsqueeze(CONSTANTS.c2, 1), 2, 1)
  _16 = torch.to(_14, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _17 = torch.index(_15, [_16])
  _18 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _19 = torch.select(torch.unsqueeze(_5, 1), 2, 9)
  _20 = torch.to(_18, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _21 = torch.index(_19, [_20])
  _22 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _23 = torch.select(torch.unsqueeze(_5, 1), 2, 6)
  _24 = torch.to(_22, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _25 = torch.index(_23, [_24])
  _26 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _27 = torch.select(torch.unsqueeze(_5, 1), 2, 15)
  _28 = torch.to(_26, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _29 = torch.index(_27, [_28])
  _30 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _31 = torch.select(torch.unsqueeze(_5, 1), 2, 0)
  _32 = torch.to(_30, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _33 = torch.index(_31, [_32])
  _34 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _35 = torch.select(torch.unsqueeze(_5, 1), 2, 8)
  _36 = torch.to(_34, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _37 = torch.index(_35, [_36])
  _38 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _39 = torch.select(torch.unsqueeze(_5, 1), 2, 4)
  _40 = torch.to(_38, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _41 = torch.index(_39, [_40])
  _42 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _43 = torch.select(torch.unsqueeze(_5, 1), 2, 3)
  _44 = torch.to(_42, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _45 = torch.index(_43, [_44])
  _46 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _47 = torch.select(torch.unsqueeze(_5, 1), 2, 10)
  _48 = torch.to(_46, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _49 = torch.index(_47, [_48])
  _50 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _51 = torch.select(torch.unsqueeze(CONSTANTS.c2, 1), 2, 0)
  _52 = torch.to(_50, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _53 = torch.index(_51, [_52])
  _54 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _55 = torch.select(torch.unsqueeze(_5, 1), 2, 13)
  _56 = torch.to(_54, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _57 = torch.index(_55, [_56])
  _58 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _59 = torch.select(torch.unsqueeze(_5, 1), 2, 14)
  _60 = torch.to(_58, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _61 = torch.index(_59, [_60])
  _62 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _63 = torch.select(torch.unsqueeze(_5, 1), 2, 5)
  _64 = torch.to(_62, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _65 = torch.index(_63, [_64])
  _66 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _67 = torch.select(torch.unsqueeze(_5, 1), 2, 1)
  _68 = torch.to(_66, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _69 = torch.index(_67, [_68])
  _70 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _71 = torch.select(torch.unsqueeze(_5, 1), 2, 12)
  _72 = torch.to(_70, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _73 = torch.index(_71, [_72])
  _74 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _75 = torch.select(torch.unsqueeze(_5, 1), 2, 2)
  _76 = torch.to(_74, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _77 = torch.index(_75, [_76])
  _78 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _79 = torch.select(torch.unsqueeze(_5, 1), 2, 7)
  _80 = torch.to(_78, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _81 = torch.index(_79, [_80])
  _82 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _83 = torch.select(torch.unsqueeze(_5, 1), 2, 3)
  _84 = torch.to(_82, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _85 = torch.index(_83, [_84])
  _86 = torch.to(CONSTANTS.c0, torch.device("cpu"), 4, False, False)
  _87 = torch.select(torch.unsqueeze(_5, 1), 2, 3)
  _88 = torch.to(_86, dtype=4, layout=0, device=torch.device("cpu"), non_blocking=False, copy=False)
  _89 = [_9, _13, _17, _21, _25, _29, _33, _37, _41, _45, _49, _53, _57, _61, _65, _69, _73, _77, _81, _85, torch.index(_87, [_88])]
  input = torch.cat(_89, 1)
  _90 = torch.t(getattr(self.Layers, "0").weight)
  _91 = torch.addmm(getattr(self.Layers, "0").bias, input, _90, beta=1, alpha=1)
  return _91
